name: generate-iso
on:
  schedule:
    - cron:
        "00 10 * * 1" # build at 10:00 UTC every Monday
  workflow_dispatch:

jobs:
  iso:
    name: Create and Upload ISO
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        image:
          - vauxite
          - vauxite-base
          - vauxite-minimal
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ISO
        id: iso
        shell: bash
        run: |
          IMAGE="ghcr.io/winblues/${{ matrix.image }}:latest"
          sudo podman run \
            --rm \
            --privileged \
            --pull=newer \
            --security-opt label=type:unconfined_t \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            -v ${{ github.workspace }}/iso/iso.toml:/config.toml:ro \
            -v ${{ github.workspace }}/output:/output \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type anaconda-iso \
            --rootfs btrfs \
            "$IMAGE"

      - name: Rename ISO and Generate Checksum
        shell: bash
        run: |
          mkdir -p output/final
          find output -name '*.iso' -exec mv {} output/final/${{ matrix.image }}-latest.iso \;
          cd output/final && sha256sum ${{ matrix.image }}-latest.iso > ${{ matrix.image }}-latest.iso-CHECKSUM

      - name: Upload ISOs and Checksum to R2
        if: github.ref_name == 'main'
        shell: bash
        env:
          RCLONE_CONFIG_R2_TYPE: s3
          RCLONE_CONFIG_R2_PROVIDER: Cloudflare
          RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_R2_REGION: auto
          RCLONE_CONFIG_R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone
          rclone copyto output/final/${{ matrix.image }}-latest.iso R2:ublue-ledif
          rclone copyto output/final/${{ matrix.image }}-latest.iso-CHECKSUM R2:ublue-ledif
