name: Generate ISO

on:
  schedule:
    - cron: "0 10 * * 1" # build at 10:00 UTC every Monday
  workflow_dispatch:

jobs:
  iso:
    name: Create and Upload ISO
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - vauxite
          - vauxite-base
          - vauxite-minimal

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set date
        shell: bash
        run: |
          echo "DATE=$(date -u +%Y%m%d)" >> "$GITHUB_ENV"

      - name: Build ISO
        shell: bash
        run: |
          IMAGE="ghcr.io/winblues/${{ matrix.image }}:latest"

          mkdir -p "$GITHUB_WORKSPACE/output"

          sudo podman pull "$IMAGE"

          sudo podman run \
            --rm \
            --privileged \
            --pull=newer \
            --security-opt label=type:unconfined_t \
            -v /var/lib/containers/storage:/var/lib/containers/storage \
            -v "$GITHUB_WORKSPACE/iso/iso.toml:/config.toml:ro" \
            -v "$GITHUB_WORKSPACE/output:/output" \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type anaconda-iso \
            --rootfs btrfs \
            --local \
            --chown "$(id -u):$(id -g)" \
            "$IMAGE"

      - name: Rename ISO and Generate Checksum
        shell: bash
        run: |
          set -euxo pipefail

          mkdir -p output/final

          mv output/bootiso/install.iso \
            "output/final/${{ matrix.image }}-${DATE}.iso"

          cd output/final

          sha256sum "${{ matrix.image }}-${DATE}.iso" \
            > "${{ matrix.image }}-${DATE}.iso-CHECKSUM"

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image }}-${{ env.DATE }}.iso
          path: |
            output/final/${{ matrix.image }}-${{ env.DATE }}.iso
            output/final/${{ matrix.image }}-${{ env.DATE }}.iso-CHECKSUM

